---
title: About this course
---

Cat ipsum dolor sit amet, see brother cat receive pets, attack out of jealousy, and demand to have some of whatever the human is cooking, then sniff the offering and walk away and meow meow you are my owner so here is a dead rat. Kitten is playing with dead mouse stare at ceiling, or stare at ceiling light stare out the window but eat the fat cats food. 

## {{< bi patch-check-fill >}} What to expect

- Cat ipsum dolor sit amet, meow to be let in. If it fits, i sits jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog. 
- Cat slides down the water slide and into pool and swims even though it does not like water. Refuse to come home when humans are going to bed; stay out all night then yowl like dying at 4am. 
- It's 3am, time to create some chaos loves cheeseburgers pet my belly, you know you want to; seize the hand and shred it! Knock over christmas tree ooooh feather moving feather! 
- Shove bum in owner's face like camera lens fish i must find my red catnip fishy fish. Hey! you there, with the hands love to play with owner's hair tie so in the middle of the night i crawl onto your chest and purr gently to help you sleep. 

## {{< bi people-fill >}} Staff info

### Unit coordinator

**Dr. Mckenzie Bryant Ipsum**  
6928231202  
mbryant55@tnayrbeiznekcm.biz



### Lecturers

**Dr. Donte Day Ipsum**  
6913353589  
dday253@yadetnod.net

**Dr. Kira Hawkins Ipsum**  
6684589592  
khawkins48@snikwaharik.com


### Demonstrators


- Hillary Horton Ipsum -- Ecology
- Kendall Jacobs Ipsum -- Microbiology
- Karla Aguilar Ipsum -- Data Science
- Carolina Williams Ipsum -- Genetics
- Callie Santos Ipsum -- Agriculture
- Tanisha Blake Ipsum -- Ecology
- Ebony Lawrence Ipsum -- Agriculture

<!-- [**{{< bi card-list >}} Unit outline**](https://www.sydney.edu.au/units)
[**{{< bi calendar >}} Timetable**](https://www.sydney.edu.au/units)
[**{{< bi chat >}} Discussion forum**](https://www.sydney.edu.au/units)
[**{{< bi disc >}} Canvas page**](https://canvas.sydney.edu.au/) -->